[project]
name = "uc-intg-psn"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "pyee>=9.0.0",
    "ucapi==0.4.0",
    "PSNAWP==3.0.1",
    "pyrate_limiter==3.9.0",
    "aiohttp>=3.13.2",
    "ucapi-framework==1.0.1",
]
