[project]
name = "uc-intg-psn"
version = "0.3.2"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.13"
dependencies = [
    "pyee~=12.0.0",
                "ucapi==0.3.1",
                "PSNAWP==3.0.1",
                "pyrate_limiter==3.9.0",
                "aiohttp>=3.13.2",
]
